### ISSUE TITLE
Python Bindings Location

### ISSUE THREAD

**Issue by chris-kuhr** [audioscience/avdecc-lib#158]
Hi *,

I am developing a Python 1722.1 Controller. Until now I wanted to wrap avbdecc-lib with Cython. I just saw the "lib/bindings/python" entry in the Directory Layout. But where is it? 
Or is this more a wish for the future?

Best Regards,
Ck

**Comment by andrew-elder** [comment]
Is this still active, or should I just close it?

**Comment by ahogen** [comment]
[Insert SpongeBob picture here]

Should probably just close it...
