### ISSUE TITLE
".gitmodules" uses 

### ISSUE THREAD

**Issue by jacky405** [audioscience/avdecc-lib#191]
The file ".gitmodules" refers to the "jdksavdecc-c" submodule using the following URL : "git@github.com:jdkoftinoff/jdksavdecc-c.git". That prevents people not owning a github account from using the repository. Using the following URL would solve the problem : "https://github.com/jdkoftinoff/jdksavdecc-c.git"

**Comment by andrew-elder** [comment]
Is setting up a github account a major hurdle for you?
I just assumed - perhaps incorrectly - that everyone would have a github account.

**Comment by jacky405** [comment]
Hello,

It is a problem for us since we want to be able to build the package on
build servers which have no github account configured. We do not want to
use any personal account's SSH keys on those servers. I also think it is
weird that a package can be cloned without github account, but some of its
submodules can not, so I guess referring to the submodule using a HTTPS URL
would just make sense since it makes things easier.

Best regards
Jacques

**Comment by andrew-elder** [comment]
Fair enough! If you wish to make the change and test it works, I'd
be happy to accept a pull request.

Regards,
Andrew

On 4/13/2015 8:47 AM, jacky405 wrote:
> Hello,
>
> It is a problem for us since we want to be able to build the package on
> build servers which have no github account configured. We do not want to
> use any personal account's SSH keys on those servers. I also think it is
> weird that a package can be cloned without github account, but some of its
> submodules can not, so I guess referring to the submodule using a HTTPS URL
> would just make sense since it makes things easier.
>
> Best regards
> Jacques
>
>
>
>
>
>
>
> On 13 April 2015 at 14:24, andrew-elder <notifications@github.com> wrote:
>
> > Is setting up a github account a major hurdle for you?
> > I just assumed - perhaps incorrectly - that everyone would have a github
> > account.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92333422>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92340610>.
>


-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by jdkoftinoff** [comment]
Submodules on github should be referred to via a relative path.

Regards,
Jeff

**Comment by andrew-elder** [comment]
That sounds even better.

On 4/13/2015 10:10 AM, Jeff Koftinoff wrote:
> Submodules on github should be referred to via a relative path.
>
> Regards,
> Jeff
>
> > On Apr 13, 2015, at 05:54, andrew-elder <notifications@github.com> wrote:
> >
> >
> > Fair enough! If you wish to make the change and test it works, I'd
> > be happy to accept a pull request.
> >
> > Regards,
> > Andrew
> >
> > On 4/13/2015 8:47 AM, jacky405 wrote:
> > > Hello,
> > >
> > > It is a problem for us since we want to be able to build the package on
> > > build servers which have no github account configured. We do not want to
> > > use any personal account's SSH keys on those servers. I also think it is
> > > weird that a package can be cloned without github account, but some 
> of its
> > > submodules can not, so I guess referring to the submodule using a 
> HTTPS URL
> > > would just make sense since it makes things easier.
> > >
> > > Best regards
> > > Jacques
> > >
> > >
> > >
> > >
> > >
> > >
> > >
> > > On 13 April 2015 at 14:24, andrew-elder <notifications@github.com> wrote:
> > >
> > > > Is setting up a github account a major hurdle for you?
> > > > I just assumed - perhaps incorrectly - that everyone would have a 
> github
> > > > account.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92333422>
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92340610>.
> > >
> >
> >
> > --
> > Andrew Elder
> > AudioScience, Inc.
> > +1-585-271-8870
> > www.audioscience.com
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92341703>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92369162>.
>


-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by andrew-elder** [comment]
Does this look like it would work
https://github.com/audioscience/avdecc-lib/pull/192/files
Jacques?



On 4/13/2015 10:10 AM, Jeff Koftinoff wrote:
> Submodules on github should be referred to via a relative path.
>
> Regards,
> Jeff
>
> > On Apr 13, 2015, at 05:54, andrew-elder <notifications@github.com> wrote:
> >
> >
> > Fair enough! If you wish to make the change and test it works, I'd
> > be happy to accept a pull request.
> >
> > Regards,
> > Andrew
> >
> > On 4/13/2015 8:47 AM, jacky405 wrote:
> > > Hello,
> > >
> > > It is a problem for us since we want to be able to build the package on
> > > build servers which have no github account configured. We do not want to
> > > use any personal account's SSH keys on those servers. I also think it is
> > > weird that a package can be cloned without github account, but some 
> of its
> > > submodules can not, so I guess referring to the submodule using a 
> HTTPS URL
> > > would just make sense since it makes things easier.
> > >
> > > Best regards
> > > Jacques
> > >
> > >
> > >
> > >
> > >
> > >
> > >
> > > On 13 April 2015 at 14:24, andrew-elder <notifications@github.com> wrote:
> > >
> > > > Is setting up a github account a major hurdle for you?
> > > > I just assumed - perhaps incorrectly - that everyone would have a 
> github
> > > > account.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > >
> > > 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92333422>
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92340610>.
> > >
> >
> >
> > --
> > Andrew Elder
> > AudioScience, Inc.
> > +1-585-271-8870
> > www.audioscience.com
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92341703>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92369162>.
>


-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by jacky405** [comment]
Yes, if that works, it looks like the perfect solution
Thanks

**Comment by andrew-elder** [comment]
My buddy "Travis CI" says it works ok!
Update has been merged to "staging" branch.

On 4/13/2015 10:58 AM, jacky405 wrote:
> Yes, if that works, it looks like the perfect solution
> Thanks
>
>
> On 13 April 2015 at 16:45, andrew-elder <notifications@github.com> wrote:
>
> >
> > Does this look like it would work
> > https://github.com/audioscience/avdecc-lib/pull/192/files
> > Jacques?
> >
> >
> >
> >
> > On 4/13/2015 10:10 AM, Jeff Koftinoff wrote:
> > > Submodules on github should be referred to via a relative path.
> > >
> > > Regards,
> > > Jeff
> > >
> > > > On Apr 13, 2015, at 05:54, andrew-elder <notifications@github.com>
> > wrote:
> > > >
> > > >
> > > > Fair enough! If you wish to make the change and test it works, I'd
> > > > be happy to accept a pull request.
> > > >
> > > > Regards,
> > > > Andrew
> > > >
> > > > On 4/13/2015 8:47 AM, jacky405 wrote:
> > > > > Hello,
> > > > >
> > > > > It is a problem for us since we want to be able to build the package
> > on
> > > > > build servers which have no github account configured. We do not
> > want to
> > > > > use any personal account's SSH keys on those servers. I also think
> > it is
> > > > > weird that a package can be cloned without github account, but some
> > > of its
> > > > > submodules can not, so I guess referring to the submodule using a
> > > HTTPS URL
> > > > > would just make sense since it makes things easier.
> > > > >
> > > > > Best regards
> > > > > Jacques
> > > > >
> > > > >
> > > > >
> > > > >
> > > > >
> > > > >
> > > > >
> > > > > On 13 April 2015 at 14:24, andrew-elder <notifications@github.com>
> > wrote:
> > > > >
> > > > > > Is setting up a github account a major hurdle for you?
> > > > > > I just assumed - perhaps incorrectly - that everyone would have a
> > > github
> > > > > > account.
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > >
> > > > >
> > > <
> > https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92333422
> > >
> > > > > > .
> > > > > >
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > >
> > > <
> > https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92340610
> > >.
> > > > >
> > > >
> > > >
> > > > --
> > > > Andrew Elder
> > > > AudioScience, Inc.
> > > > +1-585-271-8870
> > > > www.audioscience.com
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92341703
> > >.
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92369162
> > >.
> > >
> >
> >
> > --
> > Andrew Elder
> > AudioScience, Inc.
> > +1-585-271-8870
> > www.audioscience.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92386233>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/191#issuecomment-92390060>.
>


-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by jacky405** [comment]
Great ! Thanks a lot !

**Comment by jdkoftinoff** [comment]
The nice thing about using relative submodule paths is then you can make an  in-house mirror of the repositories and clone from them without needing internet access

jeff

**Comment by andrew-elder** [comment]
Corrected to use relative paths

**Comment by andrew-elder** [comment]
fixed
