### ISSUE TITLE
configuration_descriptor::get_strings_desc_string_by_reference returns pointer to free'd memory

### ISSUE THREAD

**Issue by andrew-elder** [audioscience/avdecc-lib#195]
The strings_descriptor_response class returns an uint8_t * to the corresponding string in the response class.  But, the response class is free’d before returning from the method to avoid a memory leak.  However, this frees the memory pointed to by the method returned uint8_t pointer.

**Comment by andrew-elder** [comment]
This has been fixed in staging, correct?

**Comment by vronchetti** [comment]
Yes
