### ISSUE TITLE
avdecc-lib Compile error

### ISSUE THREAD

**Issue by liruilyrics** [audioscience/avdecc-lib#213]
error C2079: “avdecc_lib::audio_unit_descriptor_imp::audio_unit_desc”uses undefined struct“avdecc_lib::jdksavdecc_descriptor_audio”
2>  audio_map_descriptor_imp.cpp

How to slove this，thanks

**Comment by andrew-elder** [comment]
What operating system?
What branch are you building?

**Comment by liruilyrics** [comment]
windows7
which branch should I build?
I am not good at English, I am sorry.

**Comment by andrew-elder** [comment]
On 8/3/2015 9:49 AM, liruilyrics wrote:
>
> windows7
> which branch should I build?
> I am not good at English, I am sorry.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/issues/213#issuecomment-127241324>.
>

W7 32-bit or 64-bit?

What compiler?

-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by liruilyrics** [comment]
W7 64-bit
VS2013

**Comment by andrew-elder** [comment]
Is this still an issue?

**Comment by andrew-elder** [comment]
Close - no response
