### ISSUE TITLE
trouble compiling

### ISSUE THREAD

**Issue by andi-hda** [audioscience/avdecc-lib#238]
Hello,

I try to setup an avb 1722.1 controller on a linux pc (fedora or ubuntu).
Trying to setup with git clone git://github.com/audioscience/avdecc-lib --recursive
fails, when it comes to Submodule 'jdksavdecc-c' after rsa fingerprint is accepted.
Message: fatal: Could not read from remote repository.

So I cloned it: git clone git://github.com/jdkoftinoff/jdksavdecc-c
which is working.
Then 
cmake . 
make
Scanning dependencies of target controller
[  2%] Building CXX object controller/lib/CMakeFiles/controller.dir/src/clock_domain_descriptor_imp.cpp.o
In file included from /home/develop/avdecc-lib/controller/lib/src/configuration_descriptor_imp.h:34:0,
from /home/develop/avdecc-lib/controller/lib/src/entity_descriptor_imp.h:33,
from /home/develop/avdecc-lib/controller/lib/src/end_station_imp.h:33,
from /home/develop/avdecc-lib/controller/lib/src/clock_domain_descriptor_imp.cpp:35:
/home/develop/avdecc-lib/controller/lib/src/audio_unit_descriptor_imp.h:40:44: error: field ‘audio_unit_desc’ has incomplete type
struct jdksavdecc_descriptor_audio audio_unit_desc; // Structure containing the audio_unit_desc fields
                                            ^
make[2]: *** [controller/lib/CMakeFiles/controller.dir/src/clock_domain_descriptor_imp.cpp.o] Error 1
make[1]: *** [controller/lib/CMakeFiles/controller.dir/all] Error 2
make: *** [all] Error 2

What did I miss to make it work ?

Thanks
andi

**Comment by andrew-elder** [comment]
If you clone jdksavdecc-c separately outside of avdecc-lib the include paths are going to be messed up. You need to do some research on way the clone --recursive failed.
I assume going
git submodule update --recursive
also gives you errors?

**Comment by andi-hda** [comment]
> git submodule update --recursive

This is doing !
THANK YOU

**Comment by andrew-elder** [comment]
Done
