### ISSUE TITLE
Q on developping Windows GUI app

### ISSUE THREAD

**Issue by JohnRama** [audioscience/avdecc-lib#308]
Hello, AVDECC lib specialist, 

I'm considering to develop Windows GUI apps using AVDECC Lib.
In order to do so, in my understanding, we need to develop the C++/CLI wrapper for AVDECC lib so that the library will work with .NET framework.

Before digging into detail, I would like to confirm if such tasks are already done before or not.
Also, I'm willing to hear the opinion if there is any other approach to develop the Windows GUI app.
Any feedback are really appreciated.

Kind Regards,
John Rama

**Comment by andrew-elder** [comment]
Hi there,
I'm not aware on any .NET wrappers for AVDECC lib.
- Andrew

**Comment by JohnRama** [comment]
Thanks for the answer. I'm fine to close this issue.
