### ISSUE TITLE
[XK-AVB-LC-SYS] Which IP Address? How to connect with switch?

### ISSUE THREAD

**Issue by wollerosekaufen** [audioscience/avdecc-lib#312]
Hello,

I want to build a network with two AVB Endpoints (XK-AVB-LC-SYS), a Laptop and an AVB Switch.
An avdecc library/controller (https://github.com/audioscience/avdecc-lib) is installed on my linux system.
The avdecc controller can be used over command line. For test purposes I have connected the endpoint with my laptop over Ethernet. But the endpoint doesn't show up in the list of the connected endpoints in the controller program.
Why not?
Can I ping the endpoint?
Do I have to config the Ethernet ports of the endpoint so that they work?

Don't know what is wrong...
Pls help.

Greetz
Chris

**Comment by sachindes** [comment]
Hello wollerosekaufen ,

Did you get solution of this?
Can you please share?

I am also facing same issue but with i210 at both ends.
Only the host i210 IP is listed, but none in the AVB network.

**Comment by wollerosekaufen** [comment]
Hello,

my AVB devices don't have an IP address at the moment. But they are 
connected to the switch and the application works!
As "peter" wrote in the thread:
     the AVB firmware is working at the layer below IP and so it doesn't 
have an IP address.
     the devices work at the level of MAC addresses and a protocol on 
top of that.
     the devices won't be able to ping unless TCP is added.

I hope I could help you.


Am 15.02.2017 um 13:02 schrieb sachindes:

**Comment by sachindes** [comment]
Thanks for info

**Comment by andrew-elder** [comment]
What software stack is running on the i210 system to do IEEE 1722.1?

**Comment by sachindes** [comment]
I did not get success with AVDECC from Open AVNu AVDECC feature branch, seems it need to extend further.  For IEEE 1722.1, I am using  AVDECC daemon referred from RCAR AVB stack. For control, I am using Audio Science avdecc cmdline console.  I am able to discover avdecc entities. 

For above issue, I need to set IP address to host i210 card. With avdecc cmdline, once i connect; I can interact with AVDECC of end stations.
