### ISSUE TITLE
" AVDECC controller command line application" on linux ubuntu 

### ISSUE THREAD

**Issue by AshlinVimal** [audioscience/avdecc-lib#314]
Hi,

I am trying to install 'AVDECC' on Linux ubuntu to recognize AVB endpoint connected.

I downloaded the source code for AVDECC library and jdksavdecc-c git repository. I was able to build it successfully.

But, I couldn't make out how to run the 'command line application' for interfacing the AVDECC controller.

I have connected 2 PCs directly (PC <--> PC). i210 cards are inserted in both PCs. 
Run avdecc commandline application on both PCs.

$ sudo ./avdecccmdline
AVDECC Controller version: v0.6.2
1 (lo, address: <127.0.0.1>)
2 (eth0, address: <10.15.1.54>)
3 (eth2, address: <192.168.1.101>)
Enter the interface number (1-3): 3

Enter "help" for a list of valid commands.
$ connect

End Station                            Instream                   Stream Format
---------------------------------------------------------------------------------

End Station                            Outstream               Stream Format
---------------------------------------------------------------------------------
$

$ list

End Station  |  Name                  |  Entity ID         |  Firmware Version  |  MAC
----------------------------------------------------------------------------------------------------

C - End Station Connected.
D - End Station Disconnected.
$

When I try to connect both PCs it is not getting connected. It is listing zero connected end stations.

Will you please help me know the steps for usage the command line application.

Do I need to provide any input arguments? 
When I do help connect it is showing as below. 

$ help connect

connect [s_e_s] [s_d_i] [d_e_s] [d_d_i] [f]
Connect an instream to an outstream.
Parameters:
  s_e_s    : the source End Station (index as int or Entity ID)
  s_d_i    : the source descriptor index (type int)
  d_e_s    : the destination End Station (index as int or Entity ID)
  d_d_i    : the destination descriptor index (type int)
  f        : the set of flags (type string)
               Valid flags are class_b, fast_connect, saved_state, streaming_wait,
               supports_encrypted, encrypted_pdu, and talker_failed.

connect [d_e_s] [d_d_i]
Display all the available outstreams for all End Stations that can connect with
the instreams.
Parameters:
  d_e_s    : the destination End Station (index as int or Entity ID)
  d_d_i    : the destination descriptor index (type int)

connect
Display all the available instreams for all End Stations.

$

I am not clear about the input arguments. Could you please help me on this.

Thanks in Advance.

Regards,
Ashlin

**Comment by andrew-elder** [comment]
What 1722.1 capable entities do you have on your network?

**Comment by AshlinVimal** [comment]
I have connected 2 PCs directly  (PC <--> PC). 
i210 cards are inserted in both PCs. OpenAVB stack is running on both PCs.
I am trying to implement AVDECC on both PCs.
Could you please let me know is there any other pre-requisite required?
What are the steps I need to follow to establish the AVDECC controller and to list the capable entities.

**Comment by andrew-elder** [comment]
The OpenAVB stack does not have any 1722.1 support in it at this time, so you won't see anything in the command line application.

**Comment by andrew-elder** [comment]
The is a branch in OpenAVB where some work has been started on this. See https://github.com/AVnu/Open-AVB/tree/feature-avdecc.

**Comment by AshlinVimal** [comment]
Thank you Andrew. :)
