### ISSUE TITLE
Single bad character on first "list" cmd

### ISSUE THREAD

**Issue by ahogen** [audioscience/avdecc-lib#344]
Not sure if this is an error because of this code or not, but I had to ask. With two AVB endpoints on the network, I launch the `avdecccmdline` utility and it finds both devices. The first time I issue the `list` command, the first entity's "Firmware" field always has this weird character. It is not specific to the device, as I've re-run avdecc multiple times and seen it grab the other device first (thereby assigning it entity index 0 and listing it first).

If I enter the `list` command a second time, the character goes away and the "Firmware" field is populated with the device's name. So it's only on the first read/print that I get this weird character (see screenshot below).

![character in firmware field](https://user-images.githubusercontent.com/6827790/27610285-92613488-5b42-11e7-8545-016c8f7bbc49.PNG)

Anything I should try on my end? Thanks and cheers!

**Comment by andrew-elder** [comment]
That's weird. We may have an error in the default constructor for the Firmware Version. What endstation are you talking to? OpenAvnu stack on i210?

**Comment by vronchetti** [comment]
Hi Alex, What platform is this on?

**Comment by ahogen** [comment]
@andrew-elder Actually, both end stations are your (AudioScience) very own Hono 4.4M devices. :smile:

@vronchetti, this is on Linux Mint 18.1 Serena (Linux 4.4.0-81-generic (x86_64), running in a VM on a Windows 7 box. Bridged ethernet adapter.

**Comment by ahogen** [comment]
Just did a clean build on an Ubuntu 16.4 VM and got identical results.

Could it be due to having an opening parenthesis as the first character of that field for some reason?

**Comment by ahogen** [comment]
Emailed a dump of this text output to myself so I can inspect it on my Windows machine. Notepad++, when View > Show Symbol > Show All Characters is set, says this character is the `RS` or "record separator" character, ASCII "30" (in base-10).

**Comment by andrew-elder** [comment]
We think we know what this is. Will take a look at it.

**Comment by vronchetti** [comment]
@ahogen Thank you for finding this
