### ISSUE TITLE
Volume control API for jdksavdecc

### ISSUE THREAD

**Issue by sachindes** [audioscience/avdecc-lib#351]
In jdksavdecc lib, there is no ready provision for Volume/gain control. It is set as customized parameter.
With ieee 1722.1 reference, I had enhanced jdksavdecc lib to control volume of entity data unit.
I had tested it on i210 environment. 

Attached avdecc aecp code snippet.

**Comment by sachindes** [comment]
![avdecc_aecp_snippet](https://user-images.githubusercontent.com/7475108/28369730-138e3392-6cb6-11e7-9d9b-011675c0c3a6.png)

**Comment by andrew-elder** [comment]
Be sure to submit a pull request to jdksavdecc lib with your updated code.

**Comment by andrew-elder** [comment]
Then we can pick it up in avdecc-lib later on.

**Comment by sachindes** [comment]
@andrew-elder ,

I have done a pull request : https://github.com/jdkoftinoff/jdksavdecc-c/pull/22

Here I have only introduced code for Volume( Audio equalizer) change for SET Control. No implementation for SET CONTROL Response. It is realized and tested along with API changes in AVDECC cmdline and AVDECC AECP.

**Comment by andrew-elder** [comment]
Great - thanks for doing that! We'll get it through the pipeline I'm sure!

**Comment by andrew-elder** [comment]
Was there are reason you don't include an implementation for the SET CONTROL response?

**Comment by sachindes** [comment]
![cmdline_volume_request-2](https://user-images.githubusercontent.com/7475108/28373364-c3764ffc-6cbf-11e7-8e84-b368e21be3c0.PNG)

**Comment by sachindes** [comment]
@andrew-elder 

My intention was to test Audio parameter control via avdecc and controller as avdecc cmdline. Response was not necessary for test evaluation.  I thought this will give ideas for some one who wish to extend customized application.

**Comment by sachindes** [comment]
As discussed, pulled in audioscience git: https://github.com/audioscience/jdksavdecc-c/pull/1

**Comment by sachindes** [comment]
closing issue on account of file merging:  https://github.com/audioscience/jdksavdecc-c/blob/master/include/jdksavdecc_jdks.h
