### ISSUE TITLE
Get/Set Configuration

### ISSUE THREAD

**Issue by avd17** [audioscience/avdecc-lib#356]
Hello,

I have recently updated my library, and am a bit confused because it seems as if I can't access any configuration but the first one.  How would one go about switching configurations? 

Thanks for any help.

**Comment by vronchetti** [comment]
Please see [here](https://github.com/audioscience/avdecc-lib/blob/master/controller/lib/include/entity_descriptor.h#L78) for the SET_CONFIGURATION API and [here](https://github.com/audioscience/avdecc-lib/blob/master/controller/app/cmdline/src/cmd_line.cpp#L3440) for example usage.

**Comment by avd17** [comment]
@vronchetti , this is how I have been setting the configuration. However if I do anything but the first configuration, it fails.

**Comment by andrew-elder** [comment]
Does the endstation device have two configurations?

**Comment by vronchetti** [comment]
@avd17 could you clarify what you mean by "it fails"?

**Comment by avd17** [comment]
The endstation has 3 configurations. I now have it working on the first and second configuration, but when sent to the 3rd one, the endstation "disappears" from the network, and my code crashes

**Comment by andrew-elder** [comment]
"It" is the endstation, or avdecc-lib?

**Comment by avd17** [comment]
I figured it out. Thanks. One more question... Can the library only access one config at a time? When I try to print out all the config info, I only can print the one I'm currently on.

**Comment by vronchetti** [comment]
@avd17 The library enumerates all configurations.  To switch between configuration and entity descriptors in avdecccmdline, use the "[Select](https://github.com/audioscience/avdecc-lib/blob/master/controller/app/cmdline/src/cmd_line.cpp#L1367)" cmd 

e.g. 
```
select [end station index] [entity index ] [configuration index]

**Comment by andrew-elder** [comment]
Endstations only have one active configuration at a time. That is per the 1722.1 specs. The library closely follows the spirit of IEEE 1722.1.

**Comment by avd17** [comment]
@andrew-elder Just for clarification, the only way to access each config info is to change the config?

**Comment by avd17** [comment]
![image](https://user-images.githubusercontent.com/30500455/28682480-c02f4f0c-72c2-11e7-9338-c953fdd6c573.png)

I can loop through and print out the config info.... but only with a second time delay between each config...

**Comment by ahogen** [comment]
@avd17, from what I understand, `select` does not change the configuration setting on the endpoint/entity. `select` is not `set`. `select` does not affect any settings on and endpoint/entity, but provides the context which other commands use. 

> $ help view details
> Display all descriptors in the currently **select**ed configuration.

... so to read configuration information without telling the entity/endpoint to change to that configuration, use `select` and `view` in `avdecccmdline`. I haven't used the shared object/dll much yet, but I assume the procedure is similar.
