### ISSUE TITLE
Strings_desc_count() only works for first configuration.

### ISSUE THREAD

**Issue by avd17** [audioscience/avdecc-lib#367]
Hello,
I am writing code in c# using your library and a managed class. I've had no success accessing strings for any configuration other than the first one. When I try to call strings_desc_count() on any configuration other than the first, it returns 0... however I know that each configuration has a count of 9+ strings. All of the other "counts"(ex. stream_input_desc_count() ) work but this one... I noticed that the use of this method was commented out in your cmd_line.cpp (starting line 1663)... The method in question is below:

    ///
    /// \return The number of Strings descriptors present in the current configuration.
    ///
    AVDECC_CONTROLLER_LIB32_API virtual size_t STDCALL strings_desc_count() = 0;

If you could provide any insights on approaches of how to fix this, or if somehow its being used wrong, or if perhaps it hasn't been completely implemented yet---help is appreciated.

Thank you.

**Comment by vronchetti** [comment]
Hi @avd17, 

I'm assuming you are up to date with the master branch?

I see one bug in our locale descriptor enumeration code: base strings descriptor index [here](https://github.com/audioscience/avdecc-lib/blob/master/controller/lib/src/end_station_imp.cpp#L627) is hardcoded to 0 when it should be ```ldr->base_strings()```

Could you post the output of the ```view_details``` cmd on two different configurations? 

>select [end station index (from cmd_list)] [entity_index] [configuration_index] 

e.g.
```
> select 1 0 0
> view details
> select 1 0 1
> view details
```

A Wireshark capture would also be helpful if you are set up to do so.

Regards,
Victor

**Comment by avd17** [comment]
@vronchetti sorry for the late response on my end. I am totally up to date with the master branch. Attached are two documents with details of both the first and second configuration (this is done WITH the edit to end_station_imp that you provided ... unfortunately still not working). Thanks
[000.txt](https://github.com/audioscience/avdecc-lib/files/1222603/000.txt)
[001.txt](https://github.com/audioscience/avdecc-lib/files/1222602/001.txt)

**Comment by avd17** [comment]
If you use the "view all" command on a config other than the first config, you will see that the list of descriptors comes back empty.

**Comment by vronchetti** [comment]
@avd17 thank you for the updated info - we clearly have a bug somewhere in our multi-configuration enumeration code.  Could you please attach a wireshark capture in a zip file?

**Comment by avd17** [comment]
[View_details_config1.zip](https://github.com/audioscience/avdecc-lib/files/1223148/View_details_config1.zip)
@vronchetti attached is the capture. I'm not very familiar with wireshark yet, so I hope this is OK.

**Comment by vronchetti** [comment]
thanks @avd17.

One more thing - could you change the [logging level](https://github.com/audioscience/avdecc-lib/blob/master/controller/app/cmdline/src/cmd_line_main.cpp#L300) to LOGGING_LEVEL_DEBUG and send over the console output of your device being enumerated?

**Comment by avd17** [comment]
[enumeration_debug.txt](https://github.com/audioscience/avdecc-lib/files/1223281/enumeration_debug.txt)
Attached. Thanks @vronchetti

**Comment by vronchetti** [comment]
@avd17 bad copy-paste bug,

see [here](https://github.com/audioscience/avdecc-lib/blob/master/controller/lib/src/end_station_imp.cpp#L465)

Please try with this change:
```diff
- log_imp_ref->post_log_msg(LOGGING_LEVEL_DEBUG, "Background read of %s index %d config %d", utility::aem_desc_value_to_name(b_next->m_type), b_next->m_index, b_first->m_config);
- read_desc_init(b_next->m_type, b_next->m_index, b_first->m_config);
+ log_imp_ref->post_log_msg(LOGGING_LEVEL_DEBUG, "Background read of %s index %d config %d", utility::aem_desc_value_to_name(b_next->m_type), b_next->m_index, b_next->m_config);
+ read_desc_init(b_next->m_type, b_next->m_index, b_next->m_config);
```

**Comment by avd17** [comment]
[enumeration_debug.txt](https://github.com/audioscience/avdecc-lib/files/1223398/enumeration_debug.txt)

**Comment by avd17** [comment]
That fixed it! Thank you for your help!
-Katie

**Comment by vronchetti** [comment]
Thank you for bringing the bug to our attention!
Regards,
Victor
